"""initial_tables

Revision ID: 4a5c7b760caa
Revises: 
Create Date: 2026-06-20 20:27:21.527577

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '4a5c7b760caa'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('trip_id', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('langsmith_run_id', sa.String(length=64), nullable=True),
    sa.Column('input', sa.JSON(), nullable=True),
    sa.Column('output', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='ai_domain'
    )
    op.create_index(op.f('ix_ai_domain_agent_runs_run_type'), 'agent_runs', ['run_type'], unique=False, schema='ai_domain')
    op.create_index(op.f('ix_ai_domain_agent_runs_status'), 'agent_runs', ['status'], unique=False, schema='ai_domain')
    op.create_index(op.f('ix_ai_domain_agent_runs_trip_id'), 'agent_runs', ['trip_id'], unique=False, schema='ai_domain')
    op.create_index(op.f('ix_ai_domain_agent_runs_user_id'), 'agent_runs', ['user_id'], unique=False, schema='ai_domain')
    op.create_table('llm_configs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='ai_domain'
    )
    op.create_index(op.f('ix_ai_domain_llm_configs_name'), 'llm_configs', ['name'], unique=True, schema='ai_domain')
    op.create_index(op.f('ix_ai_domain_llm_configs_tier'), 'llm_configs', ['tier'], unique=False, schema='ai_domain')
    op.create_table('agent_steps',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('node', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['ai_domain.agent_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='ai_domain'
    )
    op.create_index(op.f('ix_ai_domain_agent_steps_run_id'), 'agent_steps', ['run_id'], unique=False, schema='ai_domain')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_domain_agent_steps_run_id'), table_name='agent_steps', schema='ai_domain')
    op.drop_table('agent_steps', schema='ai_domain')
    op.drop_index(op.f('ix_ai_domain_llm_configs_tier'), table_name='llm_configs', schema='ai_domain')
    op.drop_index(op.f('ix_ai_domain_llm_configs_name'), table_name='llm_configs', schema='ai_domain')
    op.drop_table('llm_configs', schema='ai_domain')
    op.drop_index(op.f('ix_ai_domain_agent_runs_user_id'), table_name='agent_runs', schema='ai_domain')
    op.drop_index(op.f('ix_ai_domain_agent_runs_trip_id'), table_name='agent_runs', schema='ai_domain')
    op.drop_index(op.f('ix_ai_domain_agent_runs_status'), table_name='agent_runs', schema='ai_domain')
    op.drop_index(op.f('ix_ai_domain_agent_runs_run_type'), table_name='agent_runs', schema='ai_domain')
    op.drop_table('agent_runs', schema='ai_domain')
    # ### end Alembic commands ###
